name: Deploy to server
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing deploy to server using remote ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/home/BE-Potentivio
          git pull origin main
          docker stop potentivio_app_cont
          docker rm potentivio_app_cont
          docker build -t image_potentivio_app:latest .
          docker run -d -p 80:80 --name potentivio_app_cont image_potentivio_app:latest